export default {
  page: 1,
  total_results: 27,
  total_pages: 2,
  results: [
    {
      vote_count: 10824,
      id: 603,
      video: false,
      vote_average: 8,
      title: 'The Matrix',
      popularity: 31.850253,
      poster_path: '/hEpWvX6Bp79eLxY1kX5ZZJcme5U.jpg',
      original_language: 'en',
      original_title: 'The Matrix',
      genre_ids: [28, 878],
      backdrop_path: '/7u3pxc0K1wx32IleAkLv78MKgrw.jpg',
      adult: false,
      overview:
        'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
      release_date: '1999-03-30',
    },
    {
      vote_count: 4248,
      id: 604,
      video: false,
      vote_average: 6.7,
      title: 'The Matrix Reloaded',
      popularity: 20.818753,
      poster_path: '/ezIurBz2fdUc68d98Fp9dRf5ihv.jpg',
      original_language: 'en',
      original_title: 'The Matrix Reloaded',
      genre_ids: [12, 28, 53, 878],
      backdrop_path: '/Fp3piEuHXxKnPBO5R0Wj4wjZHg.jpg',
      adult: false,
      overview:
        "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance.  Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source.  Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
      release_date: '2003-05-15',
    },
    {
      vote_count: 3816,
      id: 605,
      video: false,
      vote_average: 6.4,
      title: 'The Matrix Revolutions',
      popularity: 19.047835,
      poster_path: '/sKogjhfs5q3azmpW7DFKKAeLEG8.jpg',
      original_language: 'en',
      original_title: 'The Matrix Revolutions',
      genre_ids: [12, 28, 53, 878],
      backdrop_path: '/pdVHUsb2eEz9ALNTr6wfRJe5xVa.jpg',
      adult: false,
      overview:
        'The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.',
      release_date: '2003-11-05',
    },
    {
      vote_count: 76,
      id: 14543,
      video: false,
      vote_average: 6.8,
      title: 'The Matrix Revisited',
      popularity: 6.783249,
      poster_path: '/kR4xt6eVdTS1agmUiL4RHXEYkDs.jpg',
      original_language: 'en',
      original_title: 'The Matrix Revisited',
      genre_ids: [99],
      backdrop_path: '/izgye3aEdT40m1audRDnRuXLaiP.jpg',
      adult: false,
      overview:
        'The film goes behind the scenes of the 1999 sci-fi movie The Matrix.',
      release_date: '2001-11-19',
    },
    {
      vote_count: 9,
      id: 221495,
      video: false,
      vote_average: 6.3,
      title: 'The Matrix Recalibrated',
      popularity: 4.283612,
      poster_path: '/sVP2PpetwT8Qg82M48tYA0ILije.jpg',
      original_language: 'en',
      original_title: 'The Matrix Recalibrated',
      genre_ids: [99, 878],
      backdrop_path: null,
      adult: false,
      overview:
        'The making of Matrix Revolutions, The (2003) is briefly touched on here in this documentary. Interviews with various cast and crew members inform us how they were affected by the deaths of Gloria Foster and Aaliyah, and also delve into the making of the visual effects that takes up a lot of screen time. Written by Rhyl Donnelly',
      release_date: '2004-04-06',
    },
    {
      vote_count: 0,
      id: 505806,
      video: false,
      vote_average: 0,
      title: 'A Glitch in the Matrix',
      popularity: 1.922583,
      poster_path: '/biW11BowXVPw4aV2mvMwOIMOQ1I.jpg',
      original_language: 'en',
      original_title: 'A Glitch in the Matrix',
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        "In 'A Glitch in the Matrix', journalist David Fuller analyzes and assesses Dr. Jordan B Peterson's recent viral interview with Cathy Newman, unpacking the deeper political, psychological and archetypal levels of the clash.",
      release_date: '2018-02-17',
    },
    {
      vote_count: 11,
      id: 26214,
      video: false,
      vote_average: 4.1,
      title: 'The American Matrix - Age Of Deception',
      popularity: 2.591381,
      poster_path: '/bQ4cjN4HJ96ddYVljgNQ64klN8k.jpg',
      original_language: 'en',
      original_title: 'The American Matrix - Age Of Deception',
      genre_ids: [99],
      backdrop_path: '/f09oCCFxLkm81WI9crc2UZzNv4F.jpg',
      adult: false,
      overview:
        'A shocking new 2 hour film by B.A. Brooks. This 2010 release is a follow up to "The Decline And Fall Of America" which was released in 2008. "The American Matrix - Age Of Deception" details news items that all people should be aware of such as the economic collapse of The United States and the formation of the a New World Order. See what has really been going on in America today.',
      release_date: '2010-01-01',
    },
    {
      vote_count: 2,
      id: 119742,
      video: false,
      vote_average: 4.5,
      title: 'The Living Matrix',
      popularity: 1.118554,
      poster_path: '/tf9MDM8oBygRSG3TALLQX6Q6tyL.jpg',
      original_language: 'de',
      original_title: 'The Living Matrix',
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        'Becker\'s documentary presents the arguments of the new-age practice of "bio-energetic medicine."  Presented as a medical documentary, The Living Matrix, promotes healing through energy reading and manipulation.  Director Greg Becker presents his arguments through anecdotal patient stories, and interviews with parapsychology professionals.',
      release_date: '2009-10-22',
    },
    {
      vote_count: 0,
      id: 344225,
      video: false,
      vote_average: 0,
      title: 'Sex and the Matrix',
      popularity: 1.003485,
      poster_path: null,
      original_language: 'en',
      original_title: 'Sex and the Matrix',
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        'A spoof created for the 2000 MTV Movie Awards, combining The Matrix and "Sex in the City".',
      release_date: '2000-01-01',
    },
    {
      vote_count: 1,
      id: 483978,
      video: false,
      vote_average: 8,
      title: 'The Matrix: ASCII',
      popularity: 1.058874,
      poster_path: '/wPtX6Rz6eo6MTzanhQlCGT089vn.jpg',
      original_language: 'en',
      original_title: 'The Matrix: ASCII',
      genre_ids: [],
      backdrop_path: '/kyPGRLsJ8owINbmnqQRgwQJs4pz.jpg',
      adult: false,
      overview: 'The Matrix rendered in ASCII',
      release_date: '2001-10-28',
    },
    {
      vote_count: 0,
      id: 503880,
      video: false,
      vote_average: 0,
      title: 'The Matrix Revolutions Revisited',
      popularity: 1.035737,
      poster_path: null,
      original_language: 'en',
      original_title: 'The Matrix Revolutions Revisited',
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview: 'The making of The Matrix Revolutions',
      release_date: '2014-12-07',
    },
    {
      vote_count: 0,
      id: 274866,
      video: false,
      vote_average: 0,
      title: 'The Roots of the Matrix',
      popularity: 1.093026,
      poster_path: '/qmOtnpPihV3Wj6ukpiNIgzo4Ax7.jpg',
      original_language: 'en',
      original_title: 'The Roots of the Matrix',
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        "Disc 8 of 10 of 'The Matrix: Ultimate Edition': Probe the philosophical and technological inspirations of The Matrix Trilogy through two insightful documentaries:  - Return to Source: Philosophy &amp; The Matrix documentary – Scholars, philosophers and theorists deconstruct the intellectual underpinnings of the trilogy  - The Hard Problem: The Science Behind the Fiction documentary – Is the notion of a real Matrix plausible? An investigation of the technologies that inspire the metaphor of the Matrix.",
      release_date: '2004-12-07',
    },
    {
      vote_count: 0,
      id: 408912,
      video: false,
      vote_average: 0,
      title: 'The Zionist Matrix of Power',
      popularity: 1.006238,
      poster_path: '/gOtayk8vKyKRnSCRn2e7sWk4ZrY.jpg',
      original_language: 'en',
      original_title: 'The Zionist Matrix of Power',
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        'The Zionist Matrix of Power is an amazing video that exposes the real seats of power in the world. It demonstrates the three most important, Media, Finance, and Politics. This video shows the extremists that now dominate this matrix that leads the West the destruction and the World to war and degeneracy.',
      release_date: '2010-12-18',
    },
    {
      vote_count: 6,
      id: 174615,
      video: false,
      vote_average: 6.6,
      title: 'Return to Source: The Philosophy of The Matrix',
      popularity: 1.230237,
      poster_path: '/4bld8IsrzXKNRRU9uCgZfWcgqAe.jpg',
      original_language: 'en',
      original_title: 'Return to Source: The Philosophy of The Matrix',
      genre_ids: [99],
      backdrop_path: '/zpY5aIOy7C8Nta86kFxGlcSMNld.jpg',
      adult: false,
      overview:
        'An hour long discussion on the philosophical concepts that inspired, and are presented in the trilogy. This is one of the two feature-length documentaries on disc number 8 of the 10-Disc Ultimate Set.',
      release_date: '2004-12-07',
    },
    {
      vote_count: 0,
      id: 323256,
      video: true,
      vote_average: 0,
      title: 'The Happiness Matrix: Creativity and Personal Mastery',
      popularity: 1.013959,
      poster_path: '/nrL7EO7Izrgr4f8ReHuc7V0omFl.jpg',
      original_language: 'en',
      original_title: 'The Happiness Matrix: Creativity and Personal Mastery',
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        '"The Happiness Matrix" is a 2-hour personal growth DVD, manifesting, in a practical, authentic and engaging manner, a powerful thought process that anyone can use to transform their lives. Sourced from wisdom traditions, "The Happiness Matrix" is a thoroughly tested and proven program based on the life-changing MBA course, "Creativity &amp; Personal Mastery", taught at some of the world\'s top ranking business schools. "The Happiness Matrix" will open you up to possibilities you never dreamed of and give you the tools you need to begin your transformation. Your internal changes will be rapidly reflected in the world outside and lead you to an immeasurably more fulfilling life. For further information, please email support@TheHappinessMatrix.com To view the Trailer, visit: http://www.thehappinessmatrix.com/trailer.html',
      release_date: '2011-08-03',
    },
    {
      vote_count: 0,
      id: 371610,
      video: false,
      vote_average: 0,
      title: 'David Icke - Secrets of the Matrix',
      popularity: 1.013475,
      poster_path: '/lysv7r5Iwn7Di5Z2Z5SORAfUoiB.jpg',
      original_language: 'en',
      original_title: 'David Icke - Secrets of the Matrix',
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        'Since 1990 David Icke has been on an amazing journey of self and collective discovery to establish the real power behind apparently "random" world events like 9/11 and the "war on terrorism".\r Here he reveals that a network of interbreeding bloodlines manipulating through their web of interconnecting secret societies have been pursuing an agenda for thousands of years to impose a globally centralized fascist state with total control and surveillance of the population.  The attacks of September 11th - not the work of "bin Laden" - and the subsequent "war on terrorism" are a means through which this is designed to be achieved.  Over more than six hours and with hundreds of illustrations, David Icke also reveals the illusion that is life in this "physical" reality. How is the "world" a provable illusion - just a lucid dream? How do we create it and how can we change the dream to one that we would like to experience?',
      release_date: '2004-10-05',
    },
    {
      vote_count: 0,
      id: 472854,
      video: false,
      vote_average: 0,
      title: "The Body as Matrix: Matthew Barney's Cremaster Cycle",
      popularity: 1,
      poster_path: null,
      original_language: 'en',
      original_title: "The Body as Matrix: Matthew Barney's Cremaster Cycle",
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        'With the five-part Cremaster Cycle of films, multi-award-winning artist Matthew Barney invented a densely layered and interconnected sculptural world that surreally combines sports, biology, sexuality, history, and mythology as it organically evolves. In this program, Barney, Guggenheim curator Nancy Spector, and others deconstruct the Cycle’s filming and subsequent translation into sculptural installations. The locations, characters, and symbols that organize the Cycle films; the Cycle installations as spatial content carriers and extensions of the performances; and objectification of the body and undifferentiated sexuality are addressed, as are the intricacies of costuming, makeup, and sculpting with Barney’s signature materials: plastic, metal, and Vaseline.',
      release_date: '',
    },
    {
      vote_count: 0,
      id: 268477,
      video: true,
      vote_average: 0,
      title: 'Adventures in Odyssey: Escape from the Forbidden Matrix',
      popularity: 1.03718,
      poster_path: '/i2ISZBxzRNnGoJoNTK2aZdleQ9S.jpg',
      original_language: 'en',
      original_title: 'Adventures in Odyssey: Escape from the Forbidden Matrix',
      genre_ids: [16, 10751],
      backdrop_path: null,
      adult: false,
      overview:
        'Dylan can\'t get enough of the new action-packed video game "Insectoids". So when he and his friend Sal are invited to play Insectoids "for real" in the virtual-reality Room of Consequence at Whit\'s End, they jump at the chance. But when the game gets too predictable, Dylan throws caution to the wind and enters the "forbidden matrix." Soon they\'re engaged in a life-sized, three-dimensional jungle war, fighting giant insect warriors and facing an even more dangerous foe.',
      release_date: '2001-01-23',
    },
    {
      vote_count: 0,
      id: 465940,
      video: false,
      vote_average: 0,
      title: "The angry face Darragh makes when people don't like the Matrix",
      popularity: 1.000022,
      poster_path: '/pI7mwKQ75umicvSO2ocN3jQbdKd.jpg',
      original_language: 'en',
      original_title:
        "The angry face Darragh makes when people don't like the Matrix",
      genre_ids: [],
      backdrop_path: null,
      adult: false,
      overview:
        'The tragic yet deeply moving story of a man so obsessed with pop culture he spends 10 minutes making a fake movie to defend the honor of the modern classic the Matrix.',
      release_date: '',
    },
    {
      vote_count: 500,
      id: 55931,
      video: false,
      vote_average: 6.9,
      title: 'The Animatrix',
      popularity: 10.403941,
      poster_path: '/1ISkdhJ48PDvETdxjllQ1AswTGv.jpg',
      original_language: 'en',
      original_title: 'The Animatrix',
      genre_ids: [16, 878],
      backdrop_path: '/2xudmFFYabaap82va87odz8FCuG.jpg',
      adult: false,
      overview:
        "Straight from the creators of the groundbreaking Matrix trilogy, this collection of short animated films from the world's leading anime directors fuses computer graphics and Japanese anime to provide the background of the Matrix universe and the conflict between man and machines. The shorts include Final Flight of the Osiris, The Second Renaissance, Kid's Story, Program, World Record, Beyond, A Detective Story and Matriculated.",
      release_date: '2003-05-09',
    },
  ],
};
